### ISSUE TITLE
Speed adjuster for triggermod

### ISSUE THREAD

**Issue by AverageVirusTotalEnjoyer** [winstxnhdw/lc-hax#102]
Make a keybind that let us toggle the speed down so we dont go at mach 2 in seconds also please try removing the turn delay i dont wanna drift

**Comment by winstxnhdw** [comment]
Unfortunately, there are only two possible options moving forward.

1. we stick with this movement controls

2. we introduce noclip controls

The controls are the way it is because we aren't implementing an entire custom movement suite for the enemies. It's just a physics rigid body and each directional key emits an impulse in that specific direction.

**Comment by AverageVirusTotalEnjoyer** [comment]
Ok

**Comment by AverageVirusTotalEnjoyer** [comment]
Whats noclip controls?

**Comment by winstxnhdw** [comment]
The enemy you possess won't experience any physics, you'll be able to phase through every object and you'll always be flying.

**Comment by AverageVirusTotalEnjoyer** [comment]
Definitely stick with current controls

**Comment by MythicalTrashcan** [comment]
> Unfortunately, there are only two possible options moving forward.
What about the spider behavior? I noticed on the realism mode that it is somewhat helpful, but what about how the spider works? Is there something that isn't letting the enemies move on their own to your camera because direct control is pretty inconvient.

**Comment by winstxnhdw** [comment]
@MythicalTrashcan I am having a lot of trouble replicating how the Spider AI follows the invisible possessed object. It seems implementing this is not going to be trivial.

**Comment by winstxnhdw** [comment]
@MythicalTrashcan this is roughly added in latest.
