### ISSUE TITLE
[FEATURE]: Dont agro centipede and nutcracker when using /hate

### ISSUE THREAD

**Issue by FredxDX** [winstxnhdw/lc-hax#221]
I love to use the /hate command or just middle click my mates but when doing so centipedes will instantly teleport on the players head. 
Same for the nutcracker, he will shoot through all walls instantly killing the player.
I want my mates feel the fear when running from the bracken and not just die instantly.

**Comment by winstxnhdw** [comment]
Sure

**Comment by winstxnhdw** [comment]
Btw, are you on latest? The nutcracker shouldn't be shooting from `/hate` anymore.

**Comment by winstxnhdw** [comment]
Honestly, I am really hesitant to drop the centipede aggro because you can have a really fun time with it by middle clicking really quickly between many other people and getting them to drop their weapons.

Currently, @armorfid just implemented a `hitclick` command, which will allow you to kill an enemy with left-click. If the centipede is an issue, you can try killing the centipede when it teleports to your friend or whenever you see it?

**Comment by FredxDX** [comment]
I haven't tested the nutcracker on the latest yet. if its already fixed then all good.
Maybe add a new command solely for the centipede. I can see the hitclick working but i dont want my mates to wonder how the centipede suddenly died.

**Comment by winstxnhdw** [comment]
Okay, here's what I can do. I'll leave the centipede aggro on middle-click but if you explicitly use `hate`, it won’t aggro the centipede.

**Comment by FredxDX** [comment]
You're a livesaver. That would perfectly fix my issue since I sometimes also like to kill people with the centipede

Also 1 question and 1 suggestion:
1. Does the requirement.bat update to the latest commit?
2. Maybe add a disclaimer for new people that slash commands cant be seen by others. I figured it out pretty fast when I started using this mod but new people might not.

**Comment by winstxnhdw** [comment]
I have made the adjustments in latest.

To answer your questions:

1. No, `launch.bat` does.
2. Sure
