### ISSUE TITLE
[Bug]:  Get Rid of .UnFake() as well 

### ISSUE THREAD

**Issue by xAstroBoy** [winstxnhdw/lc-hax#270]
### What happened?

is the same thing as doing foo == null, which makes it even more complex, just get rid of this as there's no point , just confuses the code around and it seems the unfake checks break as well a few part of the code , EX : nightVision no longer working.

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
The issue wasn't because of `Unfake` but because I accidentally removed the NOT operator in this [line](https://github.com/winstxnhdw/lc-hax/commit/fd04f4b753e44248c27ee1b09fa73d41e44a17a6#diff-79fd0599be2213a7e76092052757528fc9c755815b2b77e51a721b52d5598617R42).

In a perfect world, I wouldn't have to use `Unfake` to use the full .NET features such as pattern matching. Unfortunately, Unity did something stupid like overloading the `==` operator to return null if the object is not destroyed. See [here](https://forum.unity.com/threads/deprecation-of-operator-overload-and-fake-null-for-unityengine-object.1107368/).

The implications of this is that newer .NET features like `is` or `is not` (pattern matching) can potentially return unexpected results. Okay, so why not just avoid `is` and `is not` and do `==`? See the following example.

This is with pattern matching.

```cs
if (Helper.CurrentCamera is not Camera camera) {
    yield return waitForEndOfFrame;
    continue;
}

sunIndirect.transform.position = camera.transform.position;
```

Without pattern matching.

```cs
if (Helper.CurrentCamera == null) {
    yield return waitForEndOfFrame;
    continue;
}

sunIndirect.transform.position = Helper.CurrentCamera.transform.position;
```

Nothing wrong with this? Sure. Let's look at our implementation of `CurrentCamera`.

```cs
public static Camera? CurrentCamera =>
    Helper.LocalPlayer?.gameplayCamera.Unfake() is Camera gameplayCamera && gameplayCamera.enabled
        ? gameplayCamera
        : Helper.StartOfRound?.spectateCamera.Unfake();
```

`CurrentCamera` appears to be a property function that returns the correct camera object after performing multiple conditional checks.

Pattern matching allows us to cache `Helper.CurrentCamera` in a local variable `camera` without needing to recompute these values again.

Okay, so why not cache the variable before using it?

```cs
Camera camera  = Helper.CurrentCamera;

if (camera == null) {
    yield return waitForEndOfFrame;
    continue;
}

sunIndirect.transform.position = camera.transform.position;
```

Well, that's one extra line for every null check in our code base and we have about 200 of them and probably a lot more in the future.
