### ISSUE TITLE
hate command

### ISSUE THREAD

**Issue by TheLGAOriginal** [winstxnhdw/lc-hax#34]
could it be possible to do a /hate without making the bees leave their hive? since this attracts a lot of suspicion that there is someone with a hack

**Comment by MythicalTrashcan** [comment]
I am sure you would just need some timing. And maybe the dev could add specific enemies that will attack. It could be ```/hate <player> [enemy]```?

**Comment by joep26020** [comment]
also it just spawns enemies on the person not lure them...
still great tho

**Comment by yujispin990** [comment]
try and activate it only when they are inside the ship, they will assume someone tried to bring back the hive.

**Comment by yujispin990** [comment]
i have to add @winstxnhdw the leviathan will freeze if you try and lure it with /hate or with triggermod. It will spawn beneath a teammate and play the audio but it will stay frozen underneath the ground below them. I have no idea if i'm the only one who has this problem.

**Comment by winstxnhdw** [comment]
Yeah, we didn't really test if `hate` works on Leviathan so now we really know it doesn't.

@joep26020 Initially, `hate` simply lured enemies to a player but there are a lot of enemies that struggle pathfinding. For example, the Bunker Spider cannot leave more than 10m away from its spawn point. So we figured, it'd be funnier to just teleport the mobs straight to them. The rationale is that since the game is dark and foggy to them (unlike us), with some good timing, they wouldn't notice it teleporting to them.

**Comment by joep26020** [comment]
> Yeah, we didn't really test if `hate` works on Leviathan so at least now we really know it doesn't. I'll disable it for Leviathan soon.
> 
> @joep26020 Initially, `hate` simply lured enemies to a player but there are a lot of enemies that struggle with pathfinding. For example, the Bunker Spider cannot move more than 10m away from its spawn point. So we figured, it'd be funnier to just teleport the mobs straight to them. The rationale is that since the game is dark and foggy to them (unlike to us), with some good timing, they wouldn't notice it teleporting to them.

haha that makes a lot more sense

**Comment by winstxnhdw** [comment]
With the new enemy possession feature, you can now possess individual mobs, so this is made further obsolete.
