### ISSUE TITLE
[Enhancement]: Improve controls when possessing enemies

### ISSUE THREAD

**Issue by MythicalTrashcan** [winstxnhdw/lc-hax#46]
I have already tested the new Possession Mod and I really like this. I literal days ago was thinking of some type of mod to become one of the monsters like a Bracken or something. The only issues I saw was that some monsters do not work well in third person and they block a lot of where you look. Also, the controls are pretty wonky. I do understand this came out like 2 hours ago, but I am just listing what I tested. I tested as a Bracken first and it works well. I haven't tested if I can kill as monsters in Multiplayer or not yet, but I will sometime tomorrow. All the controls behave the same no matter the monster you possess. This is quite inconvient for very slow and fast monsters. There is some type of acceleration I see which I don't think a single monster besides like the Thumper has any acceleration. I think if possible, certain monsters possessed should have similar controls to mimic what they do. Coil heads should be fast, Brackens should be pretty slow but sneaky, and Jester should be very fast when opened. And if you can, it would be nice if you could use certain functions that the monsters do. For example, a button/keybind to start cranking as the Jester. I know this might sound like a lot, but this should be like a list to check off as stuff to add to this mod because this mod is very interesting and has a lot of potental.

**Comment by joep26020** [comment]
I agree, speed should match.

**Comment by joep26020** [comment]
> I have already tested the new Possession Mod and I really like this. I literal days ago was thinking of some type of mod to become one of the monsters like a Bracken or something. The only issues I saw was that some monsters do not work well in third person and they block a lot of where you look. Also, the controls are pretty wonky. I do understand this came out like 2 hours ago, but I am just listing what I tested. I tested as a Bracken first and it works well. I haven't tested if I can kill as monsters in Multiplayer or not yet, but I will sometime tomorrow. All the controls behave the same no matter the monster you possess. This is quite inconvient for very slow and fast monsters. There is some type of acceleration I see which I don't think a single monster besides like the Thumper has any acceleration. I think if possible, certain monsters possessed should have similar controls to mimic what they do. Coil heads should be fast, Brackens should be pretty slow but sneaky, and Jester should be very fast when opened. And if you can, it would be nice if you could use certain functions that the monsters do. For example, a button/keybind to start cranking as the Jester. I know this might sound like a lot, but this should be like a list to check off as stuff to add to this mod because this mod is very interesting and has a lot of potental.

Do you know how to use it?

**Comment by winstxnhdw** [comment]
Merry Christmas everyone!

My friend and I have been looking forward to your continued interests in our project over the past few weeks. I started this project at first to show the game and modding community that such projects can be accomplished with proper software engineering principles and decent architectural design. As the project grew larger, we focused on building funny, strange and unique non-host features, such as teleporting players, inverse teleporting players, luring enemies, and finally possessing enemies, all of which at the time of development, have not yet been introduced in this ecosystem.

With the coming of a new year and our prior commitments catching up to us, we will no longer be able to develop at such great speeds any more. Coming back to the issue at hand, @MythicalTrashcan your suggestion is valid but `Possession` is extremely experimental and there are no solidified plans to improve it any further.

Here is the breakdown:

> I think if possible, certain monsters possessed should have similar controls to mimic what they do.

We couldn't find a way to override the NavMesh Agent controls, which is why the controls are so wonky. There may be future improvements as we figure things out but no promises.

> For example, a button/keybind to start cranking as the Jester

We might add this someday, but again no promises.

Even with all that said, we are satisfied with the current state of our project and find it enjoyable to use ourselves, especially in large lobbies. I mean, it's kind of funny to see a Hydrogere moving at human speeds, a Coil-Head moving even though it is being stared at or a masked human blocking off the only exit.

Of course—contributions are always welcome but from here, our priorities will be fixing bugs and completing the initial roadplan.

**Comment by joep26020** [comment]
> Merry Christmas everyone!
> 
> My friend and I have been looking forward to your continued interests in our project over the past few weeks. I started this project at first to show the game and modding community that such projects can be accomplished with proper software engineering principles and decent architectural design. As the project grew larger, we focused on building funny, strange and unique non-host features, such as teleporting players, forcefully inverse teleporting players, automatically following players, luring enemies, and finally possessing enemies, all of which at the time of development, have not yet been introduced in this ecosystem.
> 
> With the coming of a new year and our prior commitments catching up to us, we will no longer be able to develop at such great speeds any more. Coming back to the issue at hand, @MythicalTrashcan your suggestion is valid but `Possession` is extremely experimental and there are no solidified plans to improve it any further.
> 
> Here is the breakdown:
> 
> > The only issues I saw was that some monsters do not work well in third person and they block a lot of where you look
> 
> I intend to fix this for the Eyeless Dog.
> 
> > I think if possible, certain monsters possessed should have similar controls to mimic what they do.
> 
> We couldn't find a way to override the NavMesh Agent controls, which is why the controls are so wonky. There may be future improvements as we figure things out but no promises.
> 
> > For example, a button/keybind to start cranking as the Jester
> 
> We might add this someday, but again no promises.
> 
> Even with all that said, we are satisfied with the current state of our project and find it enjoyable to use ourselves, especially in large lobbies. I mean, it's kind of funny to see a Hydrogere moving at human speeds, a Coil-Head moving even though it is being stared at or a masked human blocking off the only exit.
> 
> Of course—contributions are always welcome but from here, our priorities will be fixing bugs and completing the initial roadplan.

Merry Christmas to you too!!! I still don't know how to use possession mod lol. I try to m3 a hydrogere and it doesn't work...

**Comment by winstxnhdw** [comment]
I have replied you in the discussion.

**Comment by MythicalTrashcan** [comment]
I understand. I will be interested in the updates that release and be patient. I will still give feedback, but I basically wrote a list on what could be improved if you can in time. Merry Christmas and enjoy your day.
