### ISSUE TITLE
How do I disable certain features?

### ISSUE THREAD

**Issue by MythicalTrashcan** [winstxnhdw/lc-hax#6]
This works great, but I can't choose what I do and don't want. For example, I may not want infinite sprint, but may want clear vision. Is there some config file I haven't noticed?

**Comment by winstxnhdw** [comment]
Hey, you are right in that there is currently no way to toggle certain features during runtime, and I am not sure if this is something I want to implement yet unless I see more desire for it.

For now, however, you can disable certain features by commenting out their modules in this [file](https://github.com/winstxnhdw/lc-hax/blob/main/lc-hax/Scripts/Loader.cs).

**Comment by LTYGUY** [comment]
going ghost guys

**Comment by MythicalTrashcan** [comment]
Could you not just make all of these be mixed in with the commands? That's what I tried before I realized I couldn't disable in-game.

**Comment by winstxnhdw** [comment]
Yeah, I could but I am trying to balance user experience and customisability. I reckon that there aren’t many people who’d want to disable infinite stamina. Let’s say I do make every command toggle-able, now the user has to remember 𝑥 number more commands. I believe some opinionation is necessary.

If the reason for disabling infinite stamina is to emulate finite stamina, can’t you just stop running after a while? Spectators can’t see your stamina bar and most players can’t tell if you are running for a prolonged period because of the first-person spectator mode.
